baseurl: "/klantinteracties"
apiname: "Klantinteracties"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geopend.
nav:
  - title: Klantinteracties
    subnav:
      - title: Home
        path: /
      - title: Productvisie
        path: /productvisie
      - title: Architectuur
        path: /architectuur/architectuur
  - title: Informatiemodel
    subnav:
      - title: Basisterminologie
        path: /basisterminologie
      - title: Conceptueel model (CIM)
        path: /informatiemodel/conceptueel_model
#      - title: Uitwisselingsmodel (UGM)
#        path: /informatiemodel/uitwisselingsmodel
      - title: Gegevenswoordenboek
        path: /informatiemodel/gegevenswoordenboek
  - title: Verkenning specificaties
    subnav:
      - title: API-ontwerppatronen
        path: /api_familie_klantinteracties/klantinteracties
  - title: Achtergronddocumentatie
    subnav: 
      - title: Uitgangspunten
        path: /achtergronddocumentatie/uitgangspunten
      - title: Cases
        path: /achtergronddocumentatie/cases
      - title: Functies
        path: /achtergronddocumentatie/functies
      - title: Vragen en besluiten
        path: /achtergronddocumentatie/Vragen en besluiten    
  - title: Over
    subnav:
#      - title: Veelgestelde vragen
#        path: /veelgesteldevragen
      - title: Ontwikkeling 
        path: /ontwikkeling
      - title: Contact 
        path: /contact


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jemoji

github: VNG-Realisatie/klantinteracties

theme: jekyll-theme-time-machine

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

project_name: Klantinteracties

standard_family: nvt
